# Use goreman to run `go get github.com/mattn/goreman`

build: go build -o brokercmd ./broker/main.go && go build -o consumercmd ./consumer/main.go && go build -o producercmd ./producer/main.go

broker: ./brokercmd -port 13001
consumer1: ./consumercmd -addr localhost:13001 -count 2
consumer2: ./consumercmd -addr localhost:13001 -count 2
producer1: ./producercmd -addr localhost:13001
producer2: ./producercmd -addr localhost:13001
